### ISSUE TITLE
No response after CCR-I with empty AVP MSCC 

### ISSUE THREAD

**Issue by northmirko** [carlosedp/dcca-server-OTP#4]
Hi, many PGWs,GGSNs, dont send AVP RSU within AVP MSCC in CCR-I over Gy. It seems that code doesn't have pattern matching for this situation in server_cb.erl ?

**Comment by northmirko** [comment]
I have overcome this situation, adding pattern matching. But OTP Diameter, won't send AVPs not defined in  RFC 6733, according to Erlang docs.
I use QoS Information, Node-ID....

**Comment by carlosedp** [comment]
You probably need to define your custom .dia file importing an existing one as base and adding the required AVPs.

Would you mind posting here the pattern-matching you used for your case?

**Comment by northmirko** [comment]
Thank you for your response!!!

```
    #'Multiple-Services-Credit-Control'{
        'Used-Service-Unit' = USU,
        'Requested-Service-Unit' = RSU,
       %%'Service-Identifier' = [ServiceId],  ///It won't work with square brackets for some reason
       %%'Rating-Group' = [RatingGroup]
        'Service-Identifier' = ServiceId,
        'Rating-Group' = RatingGroup

    } = MSCC,
```
I add pattern matching for this kind of MSCC:
`15:52:53.539 [info] {#Multiple-Services-Credit-Control{'Granted-Service-Unit'=[],'Requested-Service-Unit'=[#Requested-Service-Unit{'CC-Time'=[],'CC-Total-Octets'=[],'CC-Service-Specific-Units'=[],'CC-Input-Octets'=[],'CC-Output-Octets'=[],'CC-Money'=[],'AVP'=[]}],'Used-Service-Unit'=[],'Tariff-Change-Usage'=[],'Service-Identifier'=[],'Rating-Group'="c",'Validity-Time'=[],'Result-Code'=[],'Final-Unit-Indication'=[],'Reporting-Reason'=[],'AVP'=[]}}`

I use Rating Group=99:
![image](https://user-images.githubusercontent.com/2362694/202861946-e9fc8f1f-7a2c-44ce-9d90-30d4fbce5be3.png)

```
{[], []} ->
            % Have RSU. No USU (First interrogation)
            lager:info("No RSU. No USU, MSCC AVP is present, empty MSCC"),
            prometheus_counter:inc(dcca_mscc_interrogation, [dccaserver, first]),
            {ResultCode, GrantedUnits} =
                ocsgateway:ocs_charge({initial, SessionData, {0, ServiceId, RatingGroup}});
```

handle_request (cb) is called,

**but no response is sent on wire.**

**Comment by northmirko** [comment]
I made custom dia. dict. using your file:
![image](https://user-images.githubusercontent.com/2362694/202860072-2de8012d-4f98-4342-ae1b-2ce72a1fd0b1.png)

- it compiles to .erl successfully
- CCR-I is received, code stack is traversed, but response CCA-I is not sent.
- So, I am maybe wrong about requirements from OTP/Diameter, custom AVP-a, extensions for Ro, can be received, so it must be sent ?!

I can log custom AVP in server_cb.erl from CCR-I:
`16:31:19.420 [info] {ServiceInformation, #Service-Information{'PS-Information'=[#PS-Information{'PDN-Connection-ID'=[3380600554],'Node-ID'=["PGWOT-001"],'QoS-Information'=[#QoS-Information{'QoS-Class-Identifier'=[6],'Max-Requested-Bandwidth-UL'=[8000000],'Max-Requested-Bandwidth-DL'=[42000000],'Guaranteed-Bitrate-UL'=[16000],'Guaranteed-Bitrate-DL'=[64000],'Bearer-Identifier'=[],'Allocation-Retention-Priority'=[#Allocation-Retention-Priority{'Priority-Level'=9,'Pre-emption-Capability'=[1],'Pre-emption-Vulnerability'=[1]}],'APN-Aggregate-Max-Bitrate-UL'=[8000000],'APN-Aggregate-Max-Bitrate-DL'=[42000000]}],'PDP-Address'=[{10,23,99,24}],'Called-Station-Id'=["web"],'3GPP-IMSI-MCC-MNC'=["29412"],'GGSN-Address'=[{127,0,0,69}],'SGSN-Address'=[{127,0,0,11}],'3GPP-Charging-Id'=[3380600554],'3GPP-GPRS-Neg-QoS-Profile'=[],'3GPP-Charging-Characteristics'=["0D00"],'Charging-Characteristics-Selection-Mode'=[3],'3GPP-PDP-Type'=[0],'3GPP-SGSN-MCC-MNC'=["12804"],'3GPP-GGSN-MCC-MNC'=["29617"],'CG-Address'=[],'3GPP-NSAPI'=["5"],'3GPP-Session-Stop-Indicator'=[],'3GPP-Selection-Mode'=["0"],'3GPP-RAT-Type'=[[1]],'3GPP-User-Location-Info'=[[7,84,289,86,0,11,22,755]],'3GPP-MS-Time-Zone'=[[128,0]],'Charging-Rule-Base-Name'=["0001"],'Filter-Id'=[],'PDP-Context-Type'=[0]}]}}
`

**Comment by northmirko** [comment]
I logged CCA-I,
`16:18:54.937 [info] {CCA-I: #CCA{'Session-Id'="ubuntu-hirsute;2348909712;2922784768;567643863299",'Result-Code'=2001,'Origin-Host'="example.com",'Origin-Realm'="realm.example.com",'Auth-Application-Id'=4,'CC-Request-Type'=1,'CC-Request-Number'=0,'User-Name'=[],'CC-Session-Failover'=[],'Origin-State-Id'=[],'Event-Timestamp'=[],'Multiple-Services-Credit-Control'=[#Multiple-Services-Credit-Control{'Granted-Service-Unit'=[#Granted-Service-Unit{'Tariff-Time-Change'=[],'CC-Time'=[],'CC-Input-Octets'=[],'CC-Output-Octets'=[],'CC-Total-Octets'=[300000],'CC-Service-Specific-Units'=[],'AVP'=[]}],'Requested-Service-Unit'=[],'Used-Service-Unit'=[],'Tariff-Change-Usage'=[],'Service-Identifier'=[[]],'Rating-Group'=["c"],'Validity-Time'=[3600],'Result-Code'=[2001],'Final-Unit-Indication'=[],'Reporting-Reason'=[],'AVP'=[]}],'Cost-Information'=[],'Low-Balance-Indication'=[],'Remaining-Balance'=[],'Credit-Control-Failure-Handling'=[],'Direct-Debiting-Failure-Handling'=[],'Redirect-Host'=[],'Redirect-Host-Usage'=[],'Redirect-Max-Cache-Time'=[],'Proxy-Info'=[],'Route-Record'=[],'Failed-AVP'=[],'Service-Information'=[],'AVP'=[]}}
`
 but response is not sent on wire:
![image](https://user-images.githubusercontent.com/2362694/202861019-8c2cfc9d-59a3-47a8-9661-020a4c3e2389.png)

**Comment by northmirko** [comment]
Native DCCA server (uncustomized with new AVPs) works. Any advice how to debug OTP-Diameter from ERLANG ?

**Comment by northmirko** [comment]
I found solution, minor mistake, now, your great project can fit in my test env. with custom AVPs and logic. 
Thanks. 
**Hope, Serbia will beat Brazil in football. Greetings from Serbia.**

**Comment by carlosedp** [comment]
Awesome that you made it! If you can, share it here :D Sorry I couldn't help more since I've been away from Erlang and Diameter for some years already.

Lets see on thursday... heheheeh :)

**Comment by carlosedp** [comment]
Just came here so say hi 🙋🏻🇧🇷⚽
Heheheh 😉
